version: '3.8'

services:
  db:
    image: postgres:16
    container_name: novacasa_db
    restart: always
    environment:
      POSTGRES_USER: casanova
      POSTGRES_PASSWORD: estocolmo_rubias
      POSTGRES_DB: novacasadb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
